# Spring config
management:
  endpoint:
    metrics:
      enabled: true
    web:
      exposure:
        include: metrics

spring:
  mvc:
    static-path-pattern: /static
    throw-exception-if-no-handler-found: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: Oracle12cDialect
  logging:
    level:
  #      org.springframework.boot.autoconfigure.jdbc: DEBUG
  #      com.zaxxer.hikari.HikariConfig: DEBUG
  #      com.zaxxer.hikari: TRACE
  servlet:
    multipart:
      max-file-size: 30MB
  datasource:
    backend:
      auto-commit: true
      minimum-idle: 3
      maximum-pool-size: 5
      idle-timeout: 600000 # 2 minutes
      max-lifetime: 360000 # 6 minutes
      keep-alive-time: 300000 # 5 minutes
      leak-detection-threshold: 20000 # 20 seconds
      connection-timeout: 30000 # 30 seconds
      pool-name: ecms-product-backend-pool
      jdbcUrl: jdbc:oracle:thin:@10.18.52.24:1552/TCMSPDB2
      username: PAYTECTBACKENDQA
      password: DFCC#3210
      driverClassName: oracle.jdbc.driver.OracleDriver
      test-on-borrow: true
      validationQuery: SELECT 1 FROM DUAL
    online:
      auto-commit: true
      minimum-idle: 3
      maximum-pool-size: 5
      idle-timeout: 600000 # 10 minutes
      max-lifetime: 1080000 # 18 minutes
      keep-alive-time: 300000 # 5 minutes
      leak-detection-threshold: 20000 # 20 seconds
      connection-timeout: 30000 # 30 seconds
      pool-name: ecms-product-online-pool
      jdbcUrl: jdbc:oracle:thin:@10.18.52.24:1552/TCMSPDB1
      username: PAYTECTONLINEQA
      password: DFCC#1230
      driverClassName: oracle.jdbc.driver.OracleDriver
      test-on-borrow: true
      validationQuery: SELECT 1 FROM DUAL

jwt:
  issuer: epic-cms
  secret: EPICCMSREVAMP
  token-validity: 60 # 1min
  refresh-token-validity: 300 # 5min

key:
  rsa:
    private-key:
      path: /home/appuser/PAYTECHT/key/rsa/privatekey.pem
  aes:
    path: /home/appuser/PAYTECHT/key/aes/encrypted_aes.key

# Secure delete tool path for windows
sdelete:
  path: C:/Tools/SDelete/sdelete.exe

user:
  session-validity: 16200

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

#Report module DB Connections
ecms_report_backend_connection_for_python_url: pass
ecms_report_online_connection_for_python_url: pass

#Currentstatement view
ecms_call_center_db_url: jdbc:oracle:thin:@10.18.52.24:1552/TCMSPDB2
ecms_call_center_db_username: PAYTECTONLINEQA
ecms_call_center_db_password: DFCC#1230

#EOD File upload path
eoduploadpath: "/CMS/EODFILE/"

#Scheduled Memo email sending time
cron:
  expression: "0 0 2 * * ?"

# User Idle Session Timeout
idle-timeout: 300000

tablesortmap:
  map:
    cardproductdes: cardproduct
    cardcategorydes: cardcategorycode
    maskedcrdnumber: cardnumber
    maskedcardnumber: cardnumber
    maskedcrdno: cardnumber
    maskedCardNumber: cardnumber
    cardtypedes: cardtype
    cardstatusdes: cardstatus
    promotiondes: promofeeprofilecode
    promotionstatusdes: promofeeprofilecode
    applicationId: applicationid
    creditorcash: incrementtype
    statusdes: status
    maskedcardno: maincardnumber
    accountstatus: accstatus
    pagedesc: pagetaskentityIdentity
    taskdesc: pagetaskentityIdentity
    pageActualFlag: adaflag
    pageCurrentFlag: cdaflag
    identitytypename: identificationtype
    prioritydescription: prioritylevelcode
    tag_name: tagId
    assignstatusdescription: assignstatus
    applicationdomaindes: cardappliactiondomain
    prioritylevel: prioritylevelcode
    applicationstatus: cardapplicationstatus
    productchangestatus: isproductchange
    applicationstatusdes: cardapplicationstatus
    identityno: identificationno
    assigneuser: assignuser
    cardcategorydec: cardcategorycode
    requestedUser: requesteduser
    remark: remarks
    requstuser: requesteduser
    reqcreatedtime: createdtime
    #    cardcategorydes: cardcategory
    paymentplandes: paymentplan

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://10.210.29.187:8761/eureka/
#      # defaultZone: http://10.210.29.184:8761/eureka/   # --For File Processing
#  instance:
#    hostname: 10.210.29.187
#    # hostname: 10.210.29.184   # --For File Processing
#    instanceId: "${spring.application.name}:${spring.application.instance_id:${random.value}}"
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
