# Spring config
management:
  endpoint:
    metrics:
      enabled: true
    web:
      exposure:
        include: metrics
spring:
  mvc:
    static-path-pattern: /static
    throw-exception-if-no-handler-found: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: Oracle12cDialect
  logging:
    level:
#      org.springframework.boot.autoconfigure.jdbc: DEBUG
#      com.zaxxer.hikari.HikariConfig: DEBUG
#      com.zaxxer.hikari: TRACE
  servlet:
    multipart:
      max-file-size: 30MB
  datasource:
    backend:
      auto-commit: true
      minimum-idle: 3
      maximum-pool-size: 10
      idle-timeout: 600000 # 10 minutes
      max-lifetime: 360000 # 6 minutes
      keep-alive-time: 300000 # 5 minutes
      leak-detection-threshold: 60000 # 2 minutes
      connection-timeout: 30000 # 30 seconds
      validation-timeout: 5000
      connection-test-query: SELECT 1
      pool-name: ecms-product-backend-pool
      #      public url
#      jdbcUrl: ${BACKEND_DB_URL:jdbc:oracle:thin:@192.168.2.26:1521:cmsdb}
      jdbcUrl: ${BACKEND_DB_URL:jdbc:oracle:thin:@192.168.2.25:1521:cmsdb}
      username: ${BACKEND_USERNAME:CMSBACKENDDEV}
#      username: ${BACKEND_USERNAME:CMSPRODUCTBACKEND}
      password: ${BACKEND_PASSWORD:CMSBACKENDDEV}
#      password: ${BACKEND_PASSWORD:CMSPRODUCTBACKEND}
      driverClassName: oracle.jdbc.driver.OracleDriver
      test-on-borrow: true
      validationQuery: SELECT 1 FROM DUAL
    online:
      auto-commit: true
      minimum-idle: 3
      maximum-pool-size: 10
      idle-timeout: 600000 # 10 minutes
      max-lifetime: 360000 # 6 minutes
      keep-alive-time: 300000 # 5 minutes
      leak-detection-threshold: 60000 # 2 minutes
      connection-timeout: 30000 # 30 seconds
      validation-timeout: 5000
      connection-test-query: SELECT 1
      pool-name: ecms-product-online-pool
#      jdbcUrl: ${BACKEND_DB_URL:jdbc:oracle:thin:@192.168.2.26:1521:cmsdb}
      jdbcUrl: ${ONLINE_DB_URL:jdbc:oracle:thin:@192.168.2.25:1521:cmsdb}
      #      jdbcUrl: ${BACKEND_DB_URL:jdbc:oracle:thin:@localhost:1521:orcl}
#      username: ${BACKEND_USERNAME:CMSPRODUCTONLINE}
      username: ${ONLINE_USERNAME:CMSONLINEDEV}
#      password: ${BACKEND_PASSWORD:CMSPRODUCTONLINE}
      password: ${ONLINE_PASSWORD:CMSONLINEDEV}
      driverClassName: oracle.jdbc.driver.OracleDriver
      test-on-borrow: true
      validationQuery: SELECT 1 FROM DUAL

jwt:
  issuer: epic-cms
  secret: EPICCMSREVAMP
  token-validity: 14400
  refresh-token-validity: 16200

user:
  session-validity: 16200

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

#Report module DB Connections
# ecms_report_backend_connection_for_python_url: CMSPRODUCTBACKENDDEV/CMSPRODUCTBACKENDDEV@//124.43.16.185:50170/cmsbkdb
# ecms_report_online_connection_for_python_url: CMSPRODUCTONLINEDEV/CMSPRODUCTBACKENDDEV@//124.43.16.185:50170/cmsbkdb
ecms_report_backend_connection_for_python_url: CMSBACKENDDEV/CMSBACKENDDEV@//192.168.2.25:1521/cmsdb
ecms_report_online_connection_for_python_url: CMSONLINEDEV/CMSONLINEDEV@//192.168.2.25:1521/cmsdb

#EOD File upload path
eoduploadpath: '/CMS/EODFILE/'

tablesortmap:
  map:
    cardproductdes: cardproduct
    cardcategorydes: cardcategorycode
    maskedcrdnumber: cardnumber
    maskedcardnumber: cardnumber
    maskedcrdno: cardnumber
    maskedCardNumber: cardnumber
    cardtypedes: cardtype
    cardstatusdes: cardstatus
    promotiondes: promofeeprofilecode
    promotionstatusdes: promofeeprofilecode
    applicationId: applicationid
    creditorcash: incrementtype
    statusdes: status
    maskedcardno: maincardnumber
    accountstatus: accstatus
#    idType: idtype
#    idNumber: idnumber
#    cardNumber: cardnumber
#    cardType: cardtype
#    cardProduct: cardproduct
#    cardCat: cardcategorycode
#    lastUpdatedUser: lastupdateduser
#    lastUpdatedTime: lastupdatedtime
    pagedesc: pagetaskentityIdentity
    taskdesc: pagetaskentityIdentity
    pageActualFlag: adaflag
    pageCurrentFlag: cdaflag
    identitytypename: identificationtype
    prioritydescription: prioritylevelcode
    tag_name: tagId
    assignstatusdescription: assignstatus
    applicationdomaindes: cardappliactiondomain
    prioritylevel: prioritylevelcode
    applicationstatus: cardapplicationstatus
    productchangestatus: isproductchange
    applicationstatusdes: cardapplicationstatus
    identityno: identificationno
    assigneuser: assignuser
    cardcategorydec: cardcategorycode
    requestedUser: requesteduser
    remark: remarks
    requstuser: requesteduser
    reqcreatedtime: createdtime
#    cardcategorydes: cardcategory
    paymentplandes: paymentplan
