# Spring config
management:
  endpoint:
    metrics:
      enabled: true
    web:
      exposure:
        include: metrics
spring:
  mvc:
    static-path-pattern: /static
    throw-exception-if-no-handler-found: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: Oracle12cDialect
  logging:
    level:
  servlet:
    multipart:
      max-file-size: 30MB
  datasource:
    backend:
      auto-commit: true
      minimum-idle: 15
      maximum-pool-size: 150
      idle-timeout: 300000                  # 5 min, close idle connections
      max-lifetime: 540000                 # 30 min, prevent stale connections
      keep-alive-time: 480000               # ping idle connections every 5 min
      leak-detection-threshold: 420000      # 2 min for QA only, disable in prod
      connection-timeout: 30000             # 30 sec wait for connection from pool
      validation-timeout: 5000              # 5 sec max for validation query
      connection-test-query: SELECT 1 FROM DUAL
      pool-name: ecms-product-backend-pool
      jdbcUrl: ${BACKEND_DB_URL:jdbc:oracle:thin:@192.168.1.149:1539:ORCL}
      username: ${BACKEND_USERNAME:PAYTECTBACKENDQA}
      password: ${BACKEND_PASSWORD:PAYTECTBACKENDQA}
      driverClassName: oracle.jdbc.driver.OracleDriver
      test-on-borrow: true
      validationQuery: SELECT 1 FROM DUAL
    online:
      auto-commit: true
      minimum-idle: 10
      maximum-pool-size: 100
      idle-timeout: 300000                  # 5 min, close idle connections
      max-lifetime: 540000                 # 30 min, prevent stale connections
      keep-alive-time: 480000               # ping idle connections every 5 min
      leak-detection-threshold: 420000      # 2 min for QA only, disable in prod
      connection-timeout: 30000             # 30 sec wait for connection from pool
      validation-timeout: 5000              # 5 sec max for validation query
      connection-test-query: SELECT 1 FROM DUAL
      pool-name: ecms-product-online-pool
      jdbcUrl: ${ONLINE_DB_URL:jdbc:oracle:thin:@192.168.1.149:1539:ORCL}
      username: ${ONLINE_USERNAME:PAYTECTONLINEQA }
      password: ${ONLINE_PASSWORD:PAYTECTONLINEQA }
      driverClassName: oracle.jdbc.driver.OracleDriver
      test-on-borrow: true
      validationQuery: SELECT 1 FROM DUAL

jwt:
  issuer: epic-cms
  secret: EPICCMSREVAMP
  token-validity: 14400
  refresh-token-validity: 16200

key:
  rsa:
    private-key:
      path: E:/PAYTECT/key/rsa/privatekey.pem
  aes:
    path: E:/PAYTECT/key/aes/encrypted_aes.key

user:
  session-validity: 16200

# Secure delete tool path for windows
sdelete:
  path: C:/Tools/SDelete/sdelete.exe

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

#Report module DB Connections
ecms_report_backend_connection_for_python_url: PAYTECTBACKENDQA/PAYTECTBACKENDQA@//192.168.1.149:1539/ORCL
ecms_report_online_connection_for_python_url: PAYTECTONLINEQA/PAYTECTONLINEQA@//192.168.1.149:1539/ORCL

#EOD File upload path
eoduploadpath: '/CMS/EODFILE/'

#Scheduled Memo email sending time
cron:
  expression: "0 0 2 * * ?"

# User Idle Session Timeout
idle-timeout: 300000

tablesortmap:
  map:
    cardproductdes: cardproduct
    cardcategorydes: cardcategorycode
    maskedcrdnumber: cardnumber
    maskedcardnumber: cardnumber
    maskedcrdno: cardnumber
    maskedCardNumber: cardnumber
    cardtypedes: cardtype
    cardstatusdes: cardstatus
    promotiondes: promofeeprofilecode
    promotionstatusdes: promofeeprofilecode
    applicationId: applicationid
    creditorcash: incrementtype
    statusdes: status
    maskedcardno: maincardnumber
    accountstatus: accstatus
    pagedesc: pagetaskentityIdentity
    taskdesc: pagetaskentityIdentity
    pageActualFlag: adaflag
    pageCurrentFlag: cdaflag
    identitytypename: identificationtype
    prioritydescription: prioritylevelcode
    tag_name: tagId
    assignstatusdescription: assignstatus
    applicationdomaindes: cardappliactiondomain
    prioritylevel: prioritylevelcode
    applicationstatus: cardapplicationstatus
    productchangestatus: isproductchange
    applicationstatusdes: cardapplicationstatus
    identityno: identificationno
    assigneuser: assignuser
    cardcategorydec: cardcategorycode
    requestedUser: requesteduser
    remark: remarks
    requstuser: requesteduser
    reqcreatedtime: createdtime
    paymentplandes: paymentplan