# Spring config
management:
  endpoint:
    metrics:
      enabled: true
    web:
      exposure:
        include: metrics
spring:
  mvc:
    static-path-pattern: /static
    throw-exception-if-no-handler-found: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: Oracle12cDialect
  logging:
    level:
  servlet:
    multipart:
      max-file-size: 30MB
  datasource:
    backend:
      auto-commit: true
      minimum-idle: 3
      maximum-pool-size: 5
      idle-timeout: 600000 # 10 minutes
      max-lifetime: 360000 # 6 minutes
      keep-alive-time: 300000 # 5 minutes
      leak-detection-threshold: 600000 # 2 minutes
      connection-timeout: 30000 # 30 seconds
      validation-timeout: 5000
      connection-test-query: SELECT 1
      pool-name: ecms-product-backend-pool
      jdbcUrl: ${BACKEND_DB_URL:jdbc:oracle:thin:@192.168.1.149:1539:ORCL}
      username: ${BACKEND_USERNAME:PAYTECTBACKENDDEMO }
      password: ${BACKEND_PASSWORD:PAYTECTBACKENDDEMO}
      driverClassName: oracle.jdbc.driver.OracleDriver
      test-on-borrow: true
      validationQuery: SELECT 1 FROM DUAL
    online:
      auto-commit: true
      minimum-idle: 3
      maximum-pool-size: 5
      idle-timeout: 600000 # 10 minutes
      max-lifetime: 360000 # 6 minutes
      keep-alive-time: 300000 # 5 minutes
      leak-detection-threshold: 600000 # 2 minutes
      connection-timeout: 30000 # 30 seconds
      validation-timeout: 5000
      connection-test-query: SELECT 1
      pool-name: ecms-product-online-pool
      jdbcUrl: ${ONLINE_DB_URL:jdbc:oracle:thin:@192.168.1.149:1539:ORCL}
      username: ${ONLINE_USERNAME:PAYTECTONLINEDEMO }
      password: ${ONLINE_PASSWORD:PAYTECTONLINEDEMO }
      driverClassName: oracle.jdbc.driver.OracleDriver
      test-on-borrow: true
      validationQuery: SELECT 1 FROM DUAL

jwt:
  issuer: epic-cms
  secret: EPICCMSREVAMP
  token-validity: 14400
  refresh-token-validity: 16200

user:
  session-validity: 16200

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

#Report module DB Connections
ecms_report_backend_connection_for_python_url: PAYTECTBACKENDDEMO/PAYTECTBACKENDDEMO@//192.168.1.149:1539/ORCL
ecms_report_online_connection_for_python_url: PAYTECTONLINEDEMO/PAYTECTONLINEDEMO@//192.168.1.149:1539/ORCL

#EOD File upload path
eoduploadpath: '/CMS/EODFILE/'

#Scheduled Memo email sending time
cron:
  expression: "0 0 2 * * ?"

tablesortmap:
  map:
    cardproductdes: cardproduct
    cardcategorydes: cardcategorycode
    maskedcrdnumber: cardnumber
    maskedcardnumber: cardnumber
    maskedcrdno: cardnumber
    maskedCardNumber: cardnumber
    cardtypedes: cardtype
    cardstatusdes: cardstatus
    promotiondes: promofeeprofilecode
    promotionstatusdes: promofeeprofilecode
    applicationId: applicationid
    creditorcash: incrementtype
    statusdes: status
    maskedcardno: maincardnumber
    accountstatus: accstatus
    pagedesc: pagetaskentityIdentity
    taskdesc: pagetaskentityIdentity
    pageActualFlag: adaflag
    pageCurrentFlag: cdaflag
    identitytypename: identificationtype
    prioritydescription: prioritylevelcode
    tag_name: tagId
    assignstatusdescription: assignstatus
    applicationdomaindes: cardappliactiondomain
    prioritylevel: prioritylevelcode
    applicationstatus: cardapplicationstatus
    productchangestatus: isproductchange
    applicationstatusdes: cardapplicationstatus
    identityno: identificationno
    assigneuser: assignuser
    cardcategorydec: cardcategorycode
    requestedUser: requesteduser
    remark: remarks
    requstuser: requesteduser
    reqcreatedtime: createdtime
    paymentplandes: paymentplan