# Spring config
management:
  endpoint:
    metrics:
      enabled: true
    web:
      exposure:
        include: metrics
spring:
  mvc:
    static-path-pattern: /static
    throw-exception-if-no-handler-found: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: Oracle12cDialect
  logging:
    level:
  #      org.springframework.boot.autoconfigure.jdbc: DEBUG
  #      com.zaxxer.hikari.HikariConfig: DEBUG
  #      com.zaxxer.hikari: TRACE
  servlet:
    multipart:
      max-file-size: 60MB
  datasource:
    backend:
      auto-commit: true
      minimum-idle: 3
      maximum-pool-size: 5
      idle-timeout: 600000 # 2 minutes
      max-lifetime: 360000 # 6 minutes
      keep-alive-time: 300000 # 5 minutes
      leak-detection-threshold: 20000 # 20 seconds
      connection-timeout: 30000 # 30 seconds
      pool-name: ecms-product-backend-pool
      #      public url
      #      jdbcUrl: ${BACKEND_DB_URL:jdbc:oracle:thin:@//192.168.1.149:1539/ORCL}
      #      jdbcUrl: ${BACKEND_DB_URL:jdbc:oracle:thin:@124.43.16.185:50170:cmsbkdb}
      jdbcUrl: ${BACKEND_DB_URL:jdbc:oracle:thin:@192.168.2.129:1521:orcl}
      #      username: ${BACKEND_USERNAME:PAYTECTBACKENDDEV}
      username: ${BACKEND_USERNAME:PAYTECTBACKEND}
      #      username: ${BACKEND_USERNAME:CMSPRODUCTBACKEND}
      #      password: ${BACKEND_PASSWORD:PAYTECTBACKENDDEV}
      password: ${BACKEND_PASSWORD:PAYTECTBACKEND}
      #      password: ${BACKEND_PASSWORD:CMSPRODUCTBACKEND}
      driverClassName: oracle.jdbc.driver.OracleDriver
      test-on-borrow: true
      validationQuery: SELECT 1 FROM DUAL
    online:
      auto-commit: true
      minimum-idle: 3
      maximum-pool-size: 5
      idle-timeout: 600000 # 10 minutes
      max-lifetime: 1080000 # 18 minutes
      keep-alive-time: 300000 # 5 minutes
      leak-detection-threshold: 20000 # 20 seconds
      connection-timeout: 30000 # 30 seconds
      pool-name: ecms-product-online-pool
      #      jdbcUrl: ${BACKEND_DB_URL:jdbc:oracle:thin:@//192.168.1.149:1539/ORCL}
      jdbcUrl: ${BACKEND_DB_URL:jdbc:oracle:thin:@192.168.2.128:1521:orcl}
      #      jdbcUrl: ${BACKEND_DB_URL:jdbc:oracle:thin:@localhost:1521:orcl}
      #      username: ${BACKEND_USERNAME:PAYTECTONLINEDEV}
      username: ${BACKEND_USERNAME:PAYTECTONLINE}
      #      username: ${BACKEND_USERNAME:CMSPRODUCTONLINEDEV}
      #      password: ${BACKEND_PASSWORD:PAYTECTONLINEDEV}
      password: ${BACKEND_PASSWORD:PAYTECTONLINE}
      #      password: ${BACKEND_PASSWORD:CMSPRODUCTONLINEDEV}
      driverClassName: oracle.jdbc.driver.OracleDriver
      test-on-borrow: true
      validationQuery: SELECT 1 FROM DUAL

jwt:
  issuer: epic-cms
  secret: EPICCMSREVAMP
  token-validity: 14400
  refresh-token-validity: 16200

user:
  session-validity: 16200

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

#Report module DB Connections
ecms_report_backend_connection_for_python_url: PAYTECTBACKEND/PAYTECTBACKEND@//192.168.2.129:1521/orcl
ecms_report_online_connection_for_python_url: PAYTECTONLINE/PAYTECTONLINE@//192.168.2.128:1521/orcl


#Currentstatement view
ecms_call_center_db_url: jdbc:oracle:thin:@//192.168.2.128:1521/orcl
ecms_call_center_db_username: PAYTECTBACKEND
ecms_call_center_db_password: PAYTECTBACKEND

#EOD File upload path
eoduploadpath: "/CMS/EODFILE/"

#Scheduled Memo email sending time
cron:
  expression: "0 0 2 * * ?"

# User Idle Session Timeout
idle-timeout: 300000

tablesortmap:
  map:
    cardproductdes: cardproduct
    cardcategorydes: cardcategorycode
    maskedcrdnumber: cardnumber
    maskedcardnumber: cardnumber
    maskedcrdno: cardnumber
    maskedCardNumber: cardnumber
    cardtypedes: cardtype
    cardstatusdes: cardstatus
    promotiondes: promofeeprofilecode
    promotionstatusdes: promofeeprofilecode
    applicationId: applicationid
    creditorcash: incrementtype
    statusdes: status
    maskedcardno: maincardnumber
    accountstatus: accstatus
    #    idType: idtype
    #    idNumber: idnumber
    #    cardNumber: cardnumber
    #    cardType: cardtype
    #    cardProduct: cardproduct
    #    cardCat: cardcategorycode
    #    lastUpdatedUser: lastupdateduser
    #    lastUpdatedTime: lastupdatedtime
    pagedesc: pagetaskentityIdentity
    taskdesc: pagetaskentityIdentity
    pageActualFlag: adaflag
    pageCurrentFlag: cdaflag
    identitytypename: identificationtype
    prioritydescription: prioritylevelcode
    tag_name: tagId
    assignstatusdescription: assignstatus
    applicationdomaindes: cardappliactiondomain
    prioritylevel: prioritylevelcode
    applicationstatus: cardapplicationstatus
    productchangestatus: isproductchange
    applicationstatusdes: cardapplicationstatus
    identityno: identificationno
    assigneuser: assignuser
    cardcategorydec: cardcategorycode
    requestedUser: requesteduser
    remark: remarks
    requstuser: requesteduser
    reqcreatedtime: createdtime
    #    cardcategorydes: cardcategory
    paymentplandes: paymentplan
